import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class peminjamann extends javax.swing.JFrame {
Connection con =null;
    Statement st = null;
    String user="root";
    String pswd ="";
    String host="localhost";
    String db="dbperpustakaan";
    String url="";
    private Connection Lconnection=null;
    private JTable table=null;
    /**
     * Creates new form peminjamann
     */
    public peminjamann() {
        initComponents();
         try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db +"?user=" + user + "&password="+ pswd;
            Lconnection=DriverManager.getConnection(url);
            }
            catch(ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
            }
            catch (SQLException e){
            System.out.println("koneksi gagal:" +
            e.toString());
            }
            tampilTabel();
            setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ttglpinjam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tno = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        tnpm = new javax.swing.JTextField();
        tkode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tjumlah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnsimpan = new javax.swing.JButton();
        btncek = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("NO PEMINJAMAN");

        ttglpinjam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ttglpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttglpinjamActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("ID PEMINJAM");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("NPM");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("KODE BUKU");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("JUMLAH PINJAMAN");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("TANGGAL PINJAMAN");

        tno.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });

        tnpm.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tkode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkodeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("DATA PEMINJAMAN PERPUSTAKAAN UIR");

        tjumlah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjumlahActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btncek.setText("Cek No");
        btncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tid, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(tno)
                            .addComponent(tnpm, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(tkode, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(tjumlah)
                            .addComponent(ttglpinjam))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncek)
                                .addGap(18, 18, 18)
                                .addComponent(btnedit)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnkeluar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ttglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btncek)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttglpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttglpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttglpinjamActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkodeActionPerformed

    private void tjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjumlahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user +"&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement =
            conn.prepareStatement("INSERT INTO peminjaman()" + "VALUES (?,?,?,?,?,?)");
            pStatement.setString(1, tno.getText());
            pStatement.setString(2, tid.getText());
            pStatement.setString(3, tnpm.getText());
            pStatement.setString(4, tkode.getText());
            pStatement.setString(5, tjumlah.getText());
            pStatement.setString(6, ttglpinjam.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            tampilTabel();

            pStatement.close();
            conn.close();
            tno.setText("");
            tid.setText("");
            tnpm.setText("");
            tkode.setText("");
            tjumlah.setText("");
            ttglpinjam.setText("");
        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekActionPerformed
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from peminjaman" + " where nopinjam ='" + tno.getText() + "'");
            if (rs.next()) {
                btnedit.setEnabled(true);
                tid.setText(rs.getString("id"));
                tnpm.setText(rs.getString("npm"));
                tkode.setText(rs.getString("kode"));
                tjumlah.setText(rs.getString("jumlah"));
                ttglpinjam.setText(rs.getString("tglpinjam"));
            } else {
                JOptionPane.showMessageDialog(this,"No peminjaman : Salah",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btnedit.setEnabled(false);
                tno.setText("");
                tid.setText("");
                tnpm.setText("");
                tkode.setText("");
                tjumlah.setText("");
                ttglpinjam.setText("");
                tno.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btncekActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String kode=
        table.getValueAt(table.getSelectedRow(),0).toString();
        try {
            PreparedStatement pStatement = null;
            String sql ="DELETE FROM peminjaman WHERE nopinjam=? ";
            pStatement = Lconnection.prepareStatement(sql);
            pStatement.setString(1, kode);
            int intTambah= pStatement.executeUpdate();
            if (intTambah>0)
            JOptionPane.showMessageDialog(this,
                "Hapus data sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            else
            JOptionPane.showMessageDialog(this,
                "Hapus data gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            pStatement.close();
            tampilTabel();
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {
            PreparedStatement pStatement =
            Lconnection.prepareStatement
            ("UPDATE peminjaman SET id=?,npm=?,kode=?,jumlah=?,tglpinjam=? WHERE nopinjam=?");
            pStatement.setString(1, tid.getText());
            pStatement.setString(2, tnpm.getText());
            pStatement.setString(3, tkode.getText());
            pStatement.setString(4, tjumlah.getText());
            pStatement.setString(5, ttglpinjam.getText());
            pStatement.setString(6, tno.getText());
            if ( pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,"Edit sukses",
                "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this, "Edit gagal",
                "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampilTabel();
            pStatement.close();
             tno.setText("");
                tid.setText("");
                tnpm.setText("");
                tkode.setText("");
                tjumlah.setText("");
                ttglpinjam.setText("");
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Terima Kasih Sudah Berkunjung");
        new menuutamaa().setVisible(true);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjamann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjamann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjamann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjamann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjamann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncek;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tno;
    private javax.swing.JTextField tnpm;
    private javax.swing.JTextField ttglpinjam;
    // End of variables declaration//GEN-END:variables
 private Object[][] getData(){
        Object[][] data1= null;
        try {
        Statement st = Lconnection.createStatement();
        ResultSet rs = st.executeQuery("Select * from peminjaman");
        rs.last();
        int rowCount= rs.getRow();
        rs.beforeFirst();
        data1= new Object[rowCount][6];
        int no=-1;
        while (rs.next()) {
        no=no+1;
        data1[no][0]=rs.getString("nopinjam");
        data1[no][1]=rs.getString("id");
        data1[no][2]=rs.getString("npm");
        data1[no][3]=rs.getString("kode");
        data1[no][4]=rs.getString("jumlah");
        data1[no][5]=rs.getString("tglpinjam");
        }
        st.close();
        }
        catch (SQLException e){
        System.out.println("koneksi gagal " +
                e.toString());
        }
        return data1;
        }
        private void tampilTabel() {
        String[] columnNames = {"nopinjam", "id", "npm",
        "kode", "jumlah", "tglpinjam"};
        table = new JTable(getData(), columnNames);
        jScrollPane2.setViewportView(table);
        }
}
