import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class user extends javax.swing.JFrame {
    Connection con =null;
    Statement st = null;
    String user="root";
    String pswd ="";
    String host="localhost";
    String db="dbperpustakaan";
    String url="";
    private Connection Lconnection=null;
    private JTable table=null;

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db +"?user=" + user + "&password="+ pswd;
            Lconnection=DriverManager.getConnection(url);
            }
            catch(ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
            }
            catch (SQLException e){
            System.out.println("koneksi gagal:" +
            e.toString());
            }
            tampilTabel();
            setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JButton();
        tid = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tpass = new javax.swing.JTextField();
        thak = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        btncekid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("DATA USER PERPUSTAKAAN UIR");

        btnsimpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("NAMA USER");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("ID USER");

        btnedit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("PASSWORD");

        btnhapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("HAK AKSES ");

        btnkeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        tid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });

        tnama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tpass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        thak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btncekid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btncekid.setText("Cek Id");
        btncekid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btncekid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnedit)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnkeluar)
                        .addGap(57, 57, 57)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(thak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btnsimpan)
                    .addComponent(btnkeluar)
                    .addComponent(btncekid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
         try {
        Class.forName("com.mysql.jdbc.Driver");
        url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user +"&password="+ pswd;
        Connection conn=DriverManager.getConnection(url);
        PreparedStatement pStatement =
        conn.prepareStatement("INSERT INTO user (id,nama,password,hak )" + "VALUES (?,?,?,?)");
        pStatement.setString(1, tid.getText());
        pStatement.setString(2, tnama.getText());
        pStatement.setString(3, tpass.getText());
        pStatement.setString(4, thak.getText());
        
        if (pStatement.executeUpdate()>0)
        JOptionPane.showMessageDialog(this,
        "Penambahan sukses", "Informasi",
        JOptionPane.INFORMATION_MESSAGE);

        else
        JOptionPane.showMessageDialog(this,
        "Penambahan gagal", "Informasi",
        JOptionPane.INFORMATION_MESSAGE);
        tampilTabel();
        
        pStatement.close();
        conn.close();
        tid.setText("");
        tnama.setText("");
        tpass.setText("");
        thak.setText("");
      
        }
        catch(ClassNotFoundException e) {
        System.out.println("jdbc.Driver tidak ditemukan");
            }
            catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
                }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {
            PreparedStatement pStatement =
            Lconnection.prepareStatement
            ("UPDATE user SET nama=?,password=?,hak=? WHERE id=?");
             pStatement.setString(1, tnama.getText());
             pStatement.setString(2, tpass.getText());
             pStatement.setString(3, thak.getText());
             pStatement.setString(4, tid.getText());
            if ( pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,"Edit sukses",
            "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this, "Edit gagal",
            "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampilTabel();
            pStatement.close();
             tid.setText("");
            tnama.setText("");
            tpass.setText("");
            thak.setText("");
            }
            catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
            }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String kode=
        table.getValueAt(table.getSelectedRow(),0).toString();
        try {
        PreparedStatement pStatement = null;
        String sql ="DELETE FROM user WHERE id=? ";
        pStatement = Lconnection.prepareStatement(sql);
        pStatement.setString(1, kode);
        int intTambah= pStatement.executeUpdate();
        if (intTambah>0)
        JOptionPane.showMessageDialog(this,
        "Hapus data sukses", "Informasi",
        JOptionPane.INFORMATION_MESSAGE);

        else
        JOptionPane.showMessageDialog(this,
        "Hapus data gagal", "Informasi",
        JOptionPane.INFORMATION_MESSAGE);
        pStatement.close();
        tampilTabel();
        }
        catch (SQLException e){
        System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncekidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekidActionPerformed
        try {
    Statement st = Lconnection.createStatement();
    ResultSet rs = st.executeQuery
    ("Select * from user" + " where id ='" + tid.getText() + "'");
    if (rs.next()) {
    btnedit.setEnabled(true);
    tid.setText(rs.getString("id"));
    tnama.setText(rs.getString("nama"));
    tpass.setText(rs.getString("password"));
    thak.setText(rs.getString("hak"));
    } else {
    JOptionPane.showMessageDialog(this,"Kode: Salah",
    "Informasi", JOptionPane.INFORMATION_MESSAGE);
    btnedit.setEnabled(false);
    tid.setText("");
    tnama.setText(""); 
    tpass.setText("");
    thak.setText("");
    tnama.requestFocus();
    }
}
    catch (SQLException e){
    System.out.println("koneksi gagal " + e.toString());
}
    }//GEN-LAST:event_btncekidActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
         this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Terima Kasih Sudah Berkunjung");
        new loginuser().setVisible(true);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncekid;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField thak;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tpass;
    // End of variables declaration//GEN-END:variables
 private Object[][] getData(){
        Object[][] data1= null;
        try {
        Statement st = Lconnection.createStatement();
        ResultSet rs = st.executeQuery("Select * from user");
        rs.last();
        int rowCount= rs.getRow();
        rs.beforeFirst();
        data1= new Object[rowCount][4];
        int no=-1;
        while (rs.next()) {
        no=no+1;
        data1[no][0]=rs.getString("id");
        data1[no][1]=rs.getString("nama");
        data1[no][2]=rs.getString("password");
        data1[no][3]=rs.getString("hak");
        }
        st.close();
        }
        catch (SQLException e){
        System.out.println("koneksi gagal " +
                e.toString());
        }
        return data1;
        }
        private void tampilTabel() {
        String[] columnNames = {"id", "nama", "password", "hak"};
        table = new JTable(getData(), columnNames);
        jScrollPane1.setViewportView(table);
        }
}
